Apprl-11 connect to game hub
SkillsFundingAgency/das-apprentice-learning pull request #7
Opened 2020-04-06 15:48 UTC by ben1stone

There are a number of changes in this PR 
1) Restructures the solution to use an application project and web project
2) Stop using signalR for the lobby
3) Adds a gamehub that players are connected to when both players in a lobby ready up

2020-04-07 09:08 UTC, DannyGB requested changes
I've added some general comments.
I'll not approve it whilst the jquery library files are in the check-in though as they shouldn't be in source control. The folder should be added to the .gitignore file

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application.UnitTests/Handlers/GetGame/GetGameHandlerTests.cs
> +        public async Task WhenRequestingAGame_ThenTheCorrectGameIsReturned()
What makes the game "correct" seems to be the fact that it's the game that the player is registered in.
This should be part of the test name so that it is obvious what the test is testing. "Correct" in the title doesn't really tell me anything.

You could change it to something like:

WhenRequestingAGame_ThenTheGameThePlayerIsRegisteredInIsReturned()

Creating test names is a balance between brevity and usefulness and is quite tricky to get right

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application.UnitTests/Handlers/HandlersTestBase.cs
> +        public List<Game> CreateLobbyOneGameTwoPlayers_BothNotReady()
Spacing in code files is important to readability and maintainability

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application.UnitTests/Handlers/HandlersTestBase.cs
> +        public List<Game> CreateLobbyOneGameOnePlayer()
This method name does not clearly tell the caller what it does. As this is a public method it potentially will be used by people other than yourself so it needs to be clear

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application.UnitTests/Handlers/JoinOrCreateGame/JoinOrCreateGameTestBase.cs
> +    class JoinOrCreateGameTestBase
Always specify an access modifier so that there is no ambiguity when people are reading the code.
Also the default modifier could change at any time.

Also an empty base class isn't of much use

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application.UnitTests/Handlers/JoinOrCreateGame/WhenRequestingToStartANewGame.cs
> +        }
Empty methods are of no use and make the code less readable

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application.UnitTests/Handlers/JoinOrCreateGame/WhenRequestingToStartANewGame.cs
> +        public async Task And_NoGamesExist_Then_ANewGameIsCreated()
Good test name

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application.UnitTests/Handlers/JoinOrCreateGame/WhenRequestingToStartANewGame.cs
> +            var handler = new JoinOrCreateGameHandler(Repository);
The single responsibility pattern would suggest that this handler is doing too much? It is doing both a join or a create (and join I assume). However, in this case I think it could be argued that doing it your way is valid

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application.UnitTests/Handlers/UpdatePlayerReady/WhenAPlayerClicksTheyAreReady.cs
> +        }
Remove the empty method its not needed

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application.UnitTests/Handlers/UpdatePlayerReady/WhenAPlayerClicksTheyAreReady.cs
> +        public async Task Then_TheirConnectedStatusIsUpdated()
I'd add to what status it is updated in the method name, again it removes the ambiguity.

"Then_TheirConnectedStatusIsUpdated**ToReady**"

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Handlers/GetGame/GetGameHandler.cs
> +            return _repository.Games.FirstOrDefault(g => g.Id == request.Id);
FirstOrDefault will return null when a matching item in the collections doesn't exist which means the return value of this method will also be null. This will require callers to check for null on the returned object, which can be a cause of run-time errors if they omit the check.

Take a look at the [null object pattern](https://en.wikipedia.org/wiki/Null_object_pattern) for ways to avoid this potential issue.

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Handlers/UpdatePlayerReady/UpdatePlayerReadyHandler.cs
> +
Calls into the repository should probably be async eventually? I'm guessing the repositories are fake at the moment?

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Helpers/JavascriptConvert.cs
> +        }
This seems like a code smell, are you sure it is necessary?

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Models/GameModels/GameData.cs
> +            Soldiers = new List<Soldier>() { new Soldier(1, 0, 0), new Soldier(2, 9, 9) };
I understand that at the moment this is fake data to get a working version but I'd at least put a comment into the code to explain that

You could use the task comments that then show up in the tooling such as:

[TODO] - Fake data to get working will be replaced real data in an upcoming commit

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Models/GameModels/GameSetup.cs
> +        public bool PlayersConnected { get; set; }
Could replace with 

`public bool PlayersConnected { get; set; } = false;`

then you don't need to set it in the constructor

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Models/GameModels/GameSetup.cs
> +        public int PlayersTurn { get; set; }
Could replace with

`public int PlayersTurn { get; set; } = 0;`

then you don't need to set it in the constructor

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Models/GameModels/GameSetup.cs
> +            PlayersTurn = 0;
See above comments

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Models/GameModels/GameSetup.cs
> +    public class GameSetup
This class looks like something other than "GameSetup". Looks more like a config class. I'd suggest renaming to something more appropriate

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Models/GameModels/GameSetup.cs
> +            if (Players[0] != null && Players[0].ConnectionId == connectionId)
If there can only be a set number of players per game I'd use a custom class rather than a collection. Something like

public class Players
{
    public Player PlayerOne { get; set; }
    public Player PlayerTwo { get; set}
}

That way you can get rid of the unpleasant array access notation which could potentially also be a good place for bugs to hide.

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Models/GameModels/GameSetup.cs
> +    public class GameSetup
This class seems to be doing too much and should be refactored

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Application/Repositories/GameRepository/GameRepository.cs
> +        }
Remove empty ctor

2020-04-07 09:08 UTC, DannyGB commented on src/DAS-Capture-The-Flag.Web.UnitTests/Controllers/Lobby/WhenRequestingTheLobbyIndexPage.cs
> +        public async Task ThenTheCorrectViewIsReturned()
Explain what is the "correct" view. Could be anything to someone reading the test

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/Controllers/GameController.cs
> +        private IGameRepository _repository;
Make the _repository readonly

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/Controllers/GameController.cs
> +            var game = _repository.Games.FirstOrDefault(g => g.Id == gameId);
`game` could be null and your aren't checking for it which may result in bugs, see above for null object pattern

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/Controllers/GameController.cs
> +            return View("~/Views/Game/Index.cshtml", viewModel);
Potentially unnecessary view name. If the view is in the "right" place for the framework to find it and is called the same as the action name then you don't need to specify it in the call to `View`

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/Controllers/LobbyController.cs
> +
Spacing is important

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/Controllers/LobbyController.cs
> +            return View("~/Views/Lobby/Index.cshtml", viewModel);
Again the path to the view is unnecessary if the view is in the right place for the framework to find it

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/Controllers/LobbyController.cs
> +            return JsonConvert.SerializeObject(game);
This smells, is it necessary to do a custom serialize on this object?

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/Controllers/LobbyController.cs
> +            return JsonConvert.SerializeObject(game);
This smells, is it necessary to do a custom serialize on this object?

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/Models/Game/GameViewModel.cs
> +        public Application.Models.GameModels.Game Game { get; set; }
having to fully qualify a class is usually a code smell

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/Models/Lobby/LobbyViewModel.cs
> +            Id = game.Id;
You're not checking `game` for null and then accessing a property on it.
Also if the two parameters are mandatory for the class to function then you should check them and throw ArgumentException if they're not right

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/Views/Lobby/Index.cshtml
> +    }
This smells. I'm not sure why we're doing it this way, maybe its for the SinglaR stuff?

2020-04-07 09:08 UTC, DannyGB commented on src/SFA.DAS.CaptureTheFlag.Web/wwwroot/js/Lobby.js
> +}, 1500);
Again, this smells but I'm not sure why we're doing it. Maybe it needs a re-think?

2020-04-21 14:36 UTC, ben1stone commented on src/SFA.DAS.CaptureTheFlag.Web/Hubs/GameHub.cs
> +    }
This will be updated next

2020-04-21 14:55 UTC, ben1stone commented on src/DAS-Capture-The-Flag.Application/Models/GameModels/NullGame.cs
> +        }
Here's the new NullGame class

2020-04-22 11:38 UTC, ben1stone commented on src/SFA.DAS.CaptureTheFlag.Web/Controllers/LobbyController.cs
> +        }
This is what I mentioned in the message about the view or redirect object

2020-04-22 11:40 UTC, ben1stone commented on src/SFA.DAS.CaptureTheFlag.Web/Views/Lobby/Index.cshtml
> +}, 1500);
Here's where the partial/redirect is used

2020-07-06 08:16 UTC, DannyGB approved these changes

2020-07-08 15:51 UTC, merged